name 'tko'
maintainer 'Kevin Pheasey'
maintainer_email 'kevin@kpheasey.com'
license 'all_rights'
description 'Installs/Configures opsworks_tko'
long_description 'Installs/Configures opsworks_tko'
version '0.1.0'

depends 'cloudwatch-logs'
depends 'logrotate'
depends 'opsworks_ruby'
depends 'opsworks_whenever'
depends 'swap'
